preferred_syntax = :sass
http_path = '/'
css_dir = 'assets/css'
sass_dir = 'assets/_sass'
images_dir = 'assets/img'
javascripts_dir = 'assets/js'
http_generated_images_path = "/assets/img"
relative_assets = true
line_comments = true
# output_style = :compressed